# ENPM661
#### Project 1

In [37]:
import copy
import numpy as np
input = ([[1,2,3],[8,0,5],[4,7,6]])
goal=[[1,2,3],[4,5,6],[7,8,0]]
unvisited_node=[]
visited_nodes={}
node_list=[]
Node_index_i=1
Parent_Node_index_i=0
solution_nodes=BFS(goal,input)



[(1, 1)]
value:  [[1, 2, 3], [8, 0, 5], [4, 7, 6]]
Node:  [[1, 2, 3], [0, 8, 5], [4, 7, 6]]
value:  [[1, 2, 3], [8, 0, 5], [4, 7, 6]]
Node:  [[1, 2, 3], [8, 5, 0], [4, 7, 6]]
value:  [[1, 2, 3], [8, 0, 5], [4, 7, 6]]
Node:  [[1, 0, 3], [8, 2, 5], [4, 7, 6]]
value:  [[1, 2, 3], [8, 0, 5], [4, 7, 6]]
Node:  [[1, 2, 3], [8, 7, 5], [4, 0, 6]]
[(1, 0)]
value:  [[1, 2, 3], [8, 0, 5], [4, 7, 6]]
Node:  [[1, 2, 3], [8, 0, 5], [4, 7, 6]]
Node is present
value:  [[1, 2, 3], [8, 0, 5], [4, 7, 6]]
Node:  [[0, 2, 3], [1, 8, 5], [4, 7, 6]]
value:  [[1, 2, 3], [0, 8, 5], [4, 7, 6]]
Node:  [[0, 2, 3], [1, 8, 5], [4, 7, 6]]
value:  [[1, 2, 3], [8, 0, 5], [4, 7, 6]]
Node:  [[1, 2, 3], [4, 8, 5], [0, 7, 6]]
value:  [[1, 2, 3], [0, 8, 5], [4, 7, 6]]
Node:  [[1, 2, 3], [4, 8, 5], [0, 7, 6]]
[(1, 2)]
value:  [[1, 2, 3], [8, 0, 5], [4, 7, 6]]
Node:  [[1, 2, 3], [8, 0, 5], [4, 7, 6]]
Node is present
value:  [[1, 2, 3], [8, 0, 5], [4, 7, 6]]
Node:  [[1, 2, 0], [8, 5, 3], [4, 7, 6]]
value:  [[1, 2, 3], [0, 8, 5

In [43]:
import copy
import numpy as np
def move_left(node,row,col):
    temp=node[row][col-1]
    node[row][col-1]=node[row][col]
    node[row][col]=temp
    return node
def move_right(node,row,col):
    temp=node[row][col+1]
    node[row][col+1]=node[row][col]
    node[row][col]=temp
    return node
def move_up(node,row,col):
    temp=node[row-1][col]
    node[row-1][col]=node[row][col]
    node[row][col]=temp
    return node
def move_down(node,row,col):
    temp=node[row+1][col]
    node[row+1][col]=node[row][col]
    node[row][col]=temp
    return node
def visited_node(node):
    node_dict={node[0]:{node[1]:node[2]}}
    visited_nodes.update(node_dict)
def is_already_node(node):
    for value in visited_nodes.values():
        for nest_value in value.values():
            # print("value: ", nest_value)
            # print("Node: ", node)

            if nest_value==node:
                # print("Node is present")
                return True
    return False

def BFS(goal,input,Node_index_i=1,Parent_Node_index_i=0):
    unvisited_node=[[Node_index_i,Parent_Node_index_i,input]]
    Flag=True
    # for nodes in unvisited_node:
    while Flag:
        while unvisited_node:
            nodes=unvisited_node.pop(0)
            Parent_Node_index_i+=1
            Zero=[(x,y) for x, row in enumerate(nodes[2]) for y,i in enumerate(row) if i==0]
            print(Zero)
            zero_row=Zero[0][0]
            zero_col=Zero[0][1]
            visited_node(nodes)
            if zero_col>0: 
                node_1 = move_left(copy.deepcopy(nodes[2]),zero_row,zero_col)
                if is_already_node(node_1)==False:
                    Node_index_i+=1
                    node_list.append([Node_index_i,Parent_Node_index_i,node_1])
                if node_1==goal:
                    visited_node([Node_index_i,Parent_Node_index_i,node_1])
                    print("Found node")
                    Flag=False
                    break
                
            if zero_col<2: 
                node_1 = move_right(copy.deepcopy(nodes[2]),zero_row,zero_col)
                # print(node_1)
                
                if is_already_node(node_1)==False:
                    Node_index_i+=1
                    node_list.append([Node_index_i,Parent_Node_index_i,node_1])
                if node_1==goal:
                    visited_node([Node_index_i,Parent_Node_index_i,node_1])
                    print("Found node")
                    Flag=False
                    break
            if zero_row>0: 
                node_1 = move_up(copy.deepcopy(nodes[2]),zero_row,zero_col)
                # print(node_1)
                if is_already_node(node_1)==False:
                    Node_index_i+=1
                    node_list.append([Node_index_i,Parent_Node_index_i,node_1])
                if node_1==goal:
                    visited_node([Node_index_i,Parent_Node_index_i,node_1])
                    print("Found node")
                    Flag=False
                    break
            if zero_row<2: 
                node_1 = move_down(copy.deepcopy(nodes[2]),zero_row,zero_col)
                # print(node_1)
                if is_already_node(node_1)==False:
                    Node_index_i+=1
                    node_list.append([Node_index_i,Parent_Node_index_i,node_1])
                if node_1==goal:
                    visited_node([Node_index_i,Parent_Node_index_i,node_1])
                    print("Found node")
                    Flag=False

                    break
        unvisited_node=copy.deepcopy(node_list)
        node_list.clear()  
    generated_backtracking_seq= Backtracking_node(visited_nodes)
    return generated_backtracking_seq 

def Backtracking_node(v_node):
    bk_track_seq=[]
    last_node=v_node.popitem()
    # print(last_node)
    parent_node=list(last_node[1].keys())
    # print(parent_node)
    bk_track_seq.append(list(last_node[1].values()))
    # print(bk_track_seq)

    while parent_node[0]!=0:
        gett=v_node.get(parent_node[0])
        print(gett)
        parent_node=list(gett.keys())
        bk_track_seq.append(list(gett.values()))

    return bk_track_seq

def create_nodePath_txt():
    print(solution_nodes.reverse())
    cvt_2_nparray=np.array(solution_nodes)
    cvt_2_nparray=np.squeeze(cvt_2_nparray)
    transpose_seq=cvt_2_nparray
    for k in range(len(cvt_2_nparray)):
        print (cvt_2_nparray[k])
        transpose_seq[k]=cvt_2_nparray[k].T
    # Opening and Closing a file "MyFile.txt"
    # for object name file1.
    file1 = open("nodePath.txt","w")
    for each_node in transpose_seq:
        for i in range(3):
            for j in range(3):
                file1.write(str(each_node[i][j]))
                file1.write(" ")
        file1.write("\n")        

    file1.close()

def create_NodeInfo_txt():
    print(visited_nodes.keys())
    file1 = open("NodeInfo.txt","w")
    L=[" Node_Index"," ","Parent_Node_Index", " ", "Node \n"]
    file1.writelines(L)
    for i in list(visited_nodes.keys()):
        val =visited_nodes.get(i)
        file1.write(str(i))
        file1.write("          ")
        file1.write(str(list(val.keys())[0]))
        file1.write("                ")
        j=list(val.values())
        for m in range(3):
            for n in range(3):
                file1.write(str(j[0][n][m]))
                file1.write(" ")
        file1.write("\n")
    file1.close()

def create_Nodes_txt():
    file1 = open("Nodes.txt","w")
    for i in list(visited_nodes.keys()):
        val =visited_nodes.get(i)
        j=list(val.values())
        for m in range(3):
            for n in range(3):
                file1.write(str(j[0][n][m]))
                file1.write(" ")
        file1.write("\n")
    file1.close()

# def main():
#     input = ([[1,0,3],[8,2,5],[4,7,6]])
#     goal=[[1,2,3],[4,5,6],[7,8,0]]
#     unvisited_node=[]
#     visited_nodes={}
#     node_list=[]
#     Node_index_i=1
#     Parent_Node_index_i=0
#     solution_nodes=BFS(goal,input)
#     create_nodePath_txt()
#     create_NodeInfo_txt()
#     create_Nodes_txt()

if __name__=="__main__":
    input = ([[1,0,3],[8,2,5],[4,7,6]])
    goal=[[1,2,3],[4,5,6],[7,8,0]]
    unvisited_node=[]
    visited_nodes={}
    node_list=[]
    Node_index_i=1
    Parent_Node_index_i=0
    solution_nodes=BFS(goal,input)
    create_nodePath_txt()
    create_NodeInfo_txt()
    create_Nodes_txt()


[(0, 1)]
[(0, 0)]
[(0, 2)]
[(1, 1)]
[(1, 0)]
[(1, 2)]
[(1, 0)]
[(1, 2)]
[(2, 1)]
[(1, 1)]
[(2, 0)]
[(1, 1)]
[(2, 2)]
[(0, 0)]
[(2, 0)]
[(0, 2)]
[(2, 2)]
[(2, 0)]
[(2, 2)]
[(1, 2)]
[(0, 1)]
[(2, 1)]
[(2, 1)]
[(1, 0)]
[(0, 1)]
[(2, 1)]
[(2, 1)]
[(0, 1)]
[(2, 1)]
[(0, 1)]
[(2, 1)]
[(1, 0)]
[(1, 2)]
[(0, 2)]
[(2, 2)]
[(0, 0)]
[(0, 2)]
[(2, 0)]
[(2, 2)]
[(2, 2)]
[(1, 1)]
[(0, 0)]
[(2, 0)]
[(0, 0)]
[(0, 2)]
[(2, 0)]
[(2, 2)]
[(2, 0)]
[(1, 1)]
[(0, 2)]
[(1, 1)]
[(2, 2)]
[(1, 1)]
[(0, 0)]
[(1, 1)]
[(2, 0)]
[(1, 1)]
[(1, 1)]
[(0, 0)]
[(1, 1)]
[(0, 2)]
[(0, 1)]
[(2, 1)]
[(1, 0)]
[(1, 2)]
[(1, 0)]
[(1, 2)]
[(1, 2)]
[(1, 0)]
[(1, 2)]
[(0, 1)]
[(0, 1)]
[(2, 1)]
[(1, 0)]
[(1, 2)]
[(1, 0)]
[(1, 2)]
[(1, 0)]
[(1, 0)]
[(1, 2)]
[(0, 1)]
[(1, 2)]
[(1, 0)]
[(1, 2)]
[(2, 1)]
[(1, 2)]
[(1, 0)]
[(1, 2)]
Found node
{53: [[1, 2, 3], [4, 5, 0], [7, 8, 6]]}
{29: [[1, 2, 3], [4, 0, 5], [7, 8, 6]]}
{15: [[1, 2, 3], [4, 8, 5], [7, 0, 6]]}
{7: [[1, 2, 3], [4, 8, 5], [0, 7, 6]]}
{4: [[1, 2, 3], [0, 8, 5], [4, 7, 6]]}

In [38]:
print(visited_nodes)
print(visited_nodes.values())

{1: {0: [[1, 2, 3], [8, 0, 5], [4, 7, 6]]}, 2: {1: [[1, 2, 3], [0, 8, 5], [4, 7, 6]]}, 3: {1: [[1, 2, 3], [8, 5, 0], [4, 7, 6]]}, 4: {1: [[1, 0, 3], [8, 2, 5], [4, 7, 6]]}, 5: {1: [[1, 2, 3], [8, 7, 5], [4, 0, 6]]}, 6: {2: [[0, 2, 3], [1, 8, 5], [4, 7, 6]]}, 7: {2: [[1, 2, 3], [4, 8, 5], [0, 7, 6]]}, 8: {3: [[1, 2, 0], [8, 5, 3], [4, 7, 6]]}, 9: {3: [[1, 2, 3], [8, 5, 6], [4, 7, 0]]}, 10: {4: [[0, 1, 3], [8, 2, 5], [4, 7, 6]]}, 11: {4: [[1, 3, 0], [8, 2, 5], [4, 7, 6]]}, 12: {5: [[1, 2, 3], [8, 7, 5], [0, 4, 6]]}, 13: {5: [[1, 2, 3], [8, 7, 5], [4, 6, 0]]}, 14: {6: [[2, 0, 3], [1, 8, 5], [4, 7, 6]]}, 15: {7: [[1, 2, 3], [4, 8, 5], [7, 0, 6]]}, 16: {8: [[1, 0, 2], [8, 5, 3], [4, 7, 6]]}, 17: {9: [[1, 2, 3], [8, 5, 6], [4, 0, 7]]}, 18: {10: [[8, 1, 3], [0, 2, 5], [4, 7, 6]]}, 19: {11: [[1, 3, 5], [8, 2, 0], [4, 7, 6]]}, 20: {12: [[1, 2, 3], [0, 7, 5], [8, 4, 6]]}, 21: {13: [[1, 2, 3], [8, 7, 0], [4, 6, 5]]}, 22: {14: [[2, 3, 0], [1, 8, 5], [4, 7, 6]]}, 23: {14: [[2, 8, 3], [1, 0, 5], [4,

In [28]:
def Backtracking_node(v_node):
    bk_track_seq=[]
    last_node=v_node.popitem()
    # print(last_node)
    parent_node=list(last_node[1].keys())
    # print(parent_node)
    bk_track_seq.append(list(last_node[1].values()))
    # print(bk_track_seq)

    while parent_node[0]!=0:
        gett=v_node.get(parent_node[0])
        print(gett)
        parent_node=list(gett.keys())
        bk_track_seq.append(list(gett.values()))

    return bk_track_seq

In [39]:
def create_nodePath_txt():
    print(solution_nodes.reverse())
    cvt_2_nparray=np.array(solution_nodes)
    cvt_2_nparray=np.squeeze(cvt_2_nparray)
    transpose_seq=cvt_2_nparray
    for k in range(len(cvt_2_nparray)):
        print (cvt_2_nparray[k])
        transpose_seq[k]=cvt_2_nparray[k].T
    # Opening and Closing a file "MyFile.txt"
    # for object name file1.
    file1 = open("nodePath.txt","w")
    for each_node in transpose_seq:
        for i in range(3):
            for j in range(3):
                file1.write(str(each_node[i][j]))
                file1.write(" ")
        file1.write("\n")        

    file1.close()



None
[[1 2 3]
 [8 0 5]
 [4 7 6]]
[[1 2 3]
 [0 8 5]
 [4 7 6]]
[[1 2 3]
 [4 8 5]
 [0 7 6]]
[[1 2 3]
 [4 8 5]
 [7 0 6]]
[[1 2 3]
 [4 0 5]
 [7 8 6]]
[[1 2 3]
 [4 5 0]
 [7 8 6]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]


In [40]:
def create_NodeInfo_txt():
    print(visited_nodes.keys())
    file1 = open("NodeInfo.txt","w")
    L=[" Node_Index"," ","Parent_Node_Index", " ", "Node \n"]
    file1.writelines(L)
    for i in list(visited_nodes.keys()):
        val =visited_nodes.get(i)
        file1.write(str(i))
        file1.write("          ")
        file1.write(str(list(val.keys())[0]))
        file1.write("                ")
        j=list(val.values())
        for m in range(3):
            for n in range(3):
                file1.write(str(j[0][n][m]))
                file1.write(" ")
        file1.write("\n")
    file1.close()

dict_keys([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])


In [41]:
def create_Nodes_txt():
    file1 = open("Nodes.txt","w")
    for i in list(visited_nodes.keys()):
        val =visited_nodes.get(i)
        j=list(val.values())
        for m in range(3):
            for n in range(3):
                file1.write(str(j[0][n][m]))
                file1.write(" ")
        file1.write("\n")
    file1.close()

    


    



# Dijkstra's Algorithm

In [ ]:
import cv2
import numpy as np
import heapq

# Define canvas dimensions
CANVAS_WIDTH = 1200
CANVAS_HEIGHT = 500
SCALE_FACTOR = 10  # Scaling factor for visualization

# Define costs for different movements
HORIZONTAL_VERTICAL_COST = 1
DIAGONAL_COST = 1.4

# Define allowable actions
ALLOWABLE_ACTIONS = [
    (-1, 0),  # Up
    (1, 0),   # Down
    (0, -1),  # Left
    (0, 1),   # Right
    (-1, -1), # Upper left corner
    (-1, 1),  # Upper right corner
    (1, -1),  # Bottom left corner
    (1, 1)    # Bottom right corner
]

def is_valid_move(x, y):
    return 0 < x < CANVAS_WIDTH and 0 < y < CANVAS_HEIGHT

def get_neighbors(x, y):
    neighbors = []
    for dx, dy in ALLOWABLE_ACTIONS:
        new_x, new_y = x + dx, y + dy
        if is_valid_move(new_x, new_y):
            neighbors.append((new_x, new_y))
    return neighbors

def get_distance(current, neighbor):
    dx = abs(current[0] - neighbor[0])
    dy = abs(current[1] - neighbor[1])
    if dx == 1 and dy == 1:
        return DIAGONAL_COST
    return HORIZONTAL_VERTICAL_COST

def dijkstra(start, goal):
    distances = {start: 0}
    parents = {}
    pq = [(0, start)]
    while pq:
        current_dist, current_node = heapq.heappop(pq)
        if current_node == goal:
            return distances, parents
        for neighbor in get_neighbors(*current_node):
            if ({neighbor}.issubset(Obstacle_Space)==False):
                distance = current_dist + get_distance(current_node, neighbor)
                if neighbor not in distances or distance < distances[neighbor]:
                    distances[neighbor] = distance
                    parents[neighbor] = current_node
                    heapq.heappush(pq, (distance, neighbor))
    return {}, {}  # No path found

# Create canvas image
# canvas = np.zeros((CANVAS_HEIGHT * SCALE_FACTOR, CANVAS_WIDTH * SCALE_FACTOR, 3), dtype=np.uint8)

# Example usage:
start = (10, 450)  # Start coordinate
goal = (1120, 20)  # Goal coordinate
distances, parents = dijkstra(start, goal)

canvas_4=canvas
# Draw optimal path
current_node = goal
while current_node != start:
    x1, y1 = current_node
    x2, y2 = parents[current_node]
    cv2.circle(canvas_4, (x1,500-y1), 1, [0,255,0], 1)
    
    # cv2.line(canvas, (x1 * SCALE_FACTOR, y1 * SCALE_FACTOR), (x2 * SCALE_FACTOR, y2 * SCALE_FACTOR), (0, 255, 0), 1)
    current_node = parents[current_node]

# Mark start and goal points
# cv2.circle(canvas, (start[0] * SCALE_FACTOR, start[1] * SCALE_FACTOR), 3, (0, 0, 255), -1)
# cv2.circle(canvas, (goal[0] * SCALE_FACTOR, goal[1] * SCALE_FACTOR), 3, (0, 0, 255), -1)

# Resize canvas for better visualization
# canvas = cv2.resize(canvas, (CANVAS_WIDTH, CANVAS_HEIGHT))

# Display image
cv2.imshow('Optimal Path', canvas_4)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [17]:
inp=(((4,1,2),(0,5,3),(7,8,6)),((4,1,2),(7,5,3),(0,8,6)))
# inp=[(4,1,2,3,5,6,7,8,0,9)]
set(inp)

{((4, 1, 2), (0, 5, 3), (7, 8, 6)), ((4, 1, 2), (7, 5, 3), (0, 8, 6))}

In [ ]:
gg={((4,1,2),(7,5,3),(0,8,6))}

In [20]:
inputt=[[7,6,8],[2,3,1],[5,9,0]]
s=()
ss=set()
for row in inputt:
    # for i in row:
        s=s+tuple(row)
ss.add(s)
print(s)
print(ss)        

(7, 6, 8, 2, 3, 1, 5, 9, 0)
{(7, 6, 8, 2, 3, 1, 5, 9, 0)}
